config/routes.rb
Rails.application.routes.draw do
  root 'flights#home'
  get   'home'  =>  'flights#home'
  post  'home'   =>  'flights#search'
  get   'index'  =>  'flights#index'
  post  'index'  =>  'flights#reserv'
  get   'booking'=>  'flights#new'
  post  'booking'=>  'flights#create'
  get   'buy'    =>  'flights#buy' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :users, through: :user_bookings
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :users, through: :user_flights
  has_many :user_flights
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flights, through: :user_flights
  has_many :user_bookings
  has_many :user_flights
  has_many :bookings, through: :user_bookings
  validates :email, uniqueness: true
end

app/models/user_booking.rb
class UserBooking < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/user_flight.rb
class UserFlight < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def home
    @user = User.new
  end

  def search
    data_user = [params[:home][:from], params[:home][:to], params[:home][:passengers],  params[:home][:date]]
      redirect_to controller: 'flights', action: 'index', data: data_user
  end

  def index
    data_user = params[:data]
    p data_user
    from = data_user[0]
    to = data_user[1]
    date = data_user[3]
    @passengers = data_user[2].to_i
    @flights_avaiable = Flight.where(date: date, to: to, from: from)
  end

  def reserv
    redirect_to controller: 'flights', action: 'new'
  end

  def new
    @passengers = []
    @passengers << params[:passengers].to_i
    flight = Flight.find(params[:id])
    @passengers << flight
  end

  def create
    array_comprador = []
    array_users = []
    counter = 1
    array_new = []
    b = Booking.create(flight_id: params[:id].to_i, reservation_number: rand(0..10000), total: 0)
    params.each do |key, value|
      name = "bookin" + counter.to_s
      email = "booking" + counter.to_s
      if key == name
         array_new << value
      elsif key == email
         array_new << value
         array_users << array_new
         array_new = []
         counter += 1 
      elsif key == "name_c"
        array_comprador << value
      elsif key == "email_c"
        array_comprador << value
        @user = User.create(name: array_comprador[0], email: array_comprador[1])
        flight = Flight.find(params[:id]) 
        UserFlight.create(user_id: @user.id, flight_id: flight.id) 
        passengers = flight.passengers - params[:passengers].to_i
        flight.update(passengers: passengers)
        @booking = Booking.last
        p "**"*50
        p @user
        user_booking = UserBooking.create(user_id: @user.id, booking_id: @booking.id)   
        p "-" * 50      
        p user_booking
      end  
    end
    array_users.each do |user|
      User.create(name: user[0], email: user[1])
    end
    total = array_users.count * Flight.find(params[:id]).cost
    b.update(total: total)
    redirect_to controller: 'flights', action: 'buy', data: @booking
  end

  def buy
     @booking = Booking.find(params[:data].to_i)
     @flight = @booking.flight
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/buy.html.erb
<h1>Su compra:</h1>
<h3>Numero de reservacion: 00<%= @booking.id %></h3>
<h3>From: <%= @flight.from %></h3>
<h3>To: <%= @flight.to %></h3>
<h3>Date: <%= @flight.date %></h3>
<h3>Total a pagar: $ <%= @booking.total %> </h3>
<h3>Id de la reservacion: <%= @booking.reservation_number %> </h3>

<hr><hr>

app/views/flights/home.html.erb
<h1 align="center">Compra tus tickets aqui!</h1>
<div align="center">
  <%= form_for :home, url: home_path  do |f| %>
    <%= f.label :From %>
    <%= f.text_field :from%><br>
    <br>
    <%= f.label :To %>
    <%= f.text_field :to%><br>
    <br>
    <%= f.label :Pasajeros %>
    <%= f.text_field :passengers%><br>
    <br>
    <%= f.label :Date %>
    <%= f.date_field :date%><br>
    <br>
    <%= f.submit "Encuentra tus boletos"%>
  <% end %>
</div>

app/views/flights/index.html.erb
<h1>Selecciona tu vuelo</h1>
<% @flights_avaiable.each do |t| %>
  <p><%= t.id %></p>
  <br>
  <h3>From: </h3>
  <br>
  <p><%= t.from %></p>
  <br>
  <h3>To: </h3>
  <p><%= t.to %></p>
  <h3>Date: </h3>
  <p><%= t.date %></p>
  <h3>Passengers avaiables: </h3>
  <p><%= t.passengers %></p>
  <%= link_to "Elige este vuelo", controller: 'flights', action: 'new', id: t.id, passengers: @passengers %>
  <hr>
<% end %>

app/views/flights/new.html.erb
<h1>Llena los datos de tus tickets</h1>

<div>
  <%= form_for :booking, url: booking_path(:id => @passengers[1].id, :passengers => @passengers[0]) do |f| %>
    <% for i in 1..@passengers[0] %>
    <p>Datos de pasajero: <%= i %></p>
      <%= f.label :Name %>
      <%= f.text_field :name, name: "bookin#{i.to_s}" %><br>

      <%= f.label :Email %>
      <%= f.text_field :email, name: "booking#{i.to_s}" %><br>
    <% end %>
    <p>Aqui van los datos del comprador</p>
    <%= f.label :Name %>
      <%= f.text_field :name, name: "name_c" %><br>
    <%= f.label :Email %>
      <%= f.text_field :email, name: "email_c" %><br>

    <%= f.submit "Comprar", data: { confirm: "Esta usted seguro?"} %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenFase3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>